version: '3.8'

networks:
  inception:
    driver: bridge

services:
  mariadb:
    container_name: ym_mariadb
    build:
      context: ./requirements/mariadb/
      dockerfile: Dockerfile
    image: mariadb_image
    restart: always
    networks:
      - inception
    volumes:
      - volume_mariadb:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${NAME_DATABASE}
      MYSQL_USER: ${USER_NAME}
      MYSQL_PASSWORD: ${USER_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
    secrets:
      - db_name
      - db_user_name
      - db_user_password
      - db_root_password
  wordpress:
      container_name: ym_wordpress
      build:
        context: ./requirements/wordpress
        dockerfile: Dockerfile
      image: wordpress_image
      restart: always
      volumes:
      - volume_wordpress_nginx:/var/www/html/wordpress
      networks:
        - inception
      expose:
        - "9000"
      depends_on:
      - mariadb
      environment:
        MYSQL_DATABASE : ${NAME_DATABASE}
        MYSQL_USER : ${USER_NAME}
        MYSQL_PASSWORD : ${USER_PASSWORD}
        LOCALHOST : ${DB_HOST}
        TITLE : ${TITLE}
        URL_WP : ${URL_WP}
        ADMIN_WP : ${ADMIN_WP}
        ADMIN_PASSWORD_WP : ${ADMIN_PASSWORD_WP}
        ADMIN_EMAIL_WP : ${ADMIN_EMAIL_WP}
        USER_WP : ${USER_WP}
        USER_PASSWORD_WP : ${USER_PASSWORD_WP}
        USER_EMAIL_WP : ${USER_EMAIL_WP}
      secrets:
        - db_name
        - db_user_name
        - db_user_password
        - db_hostname
        - wp_admin
        - wp_admin_password
        - wp_admin_email
        - wp_user_password
        - wp_user_email
  nginx:
        container_name: ym_nginx
        build:
          context: ./requirements/nginx
          dockerfile: Dockerfile
        image: nginx_image
        restart: always
        volumes:
        - volume_wordpress_nginx:/var/www/html/wordpress
        networks:
          - inception
        depends_on:
        - mariadb
        - wordpress
        ports:
        - "443:443"
volumes:
  volume_mariadb:
    driver_opts:
      type: none
      o: bind
      device: ${PATH_VM_MARIADB}
  volume_wordpress_nginx:
    driver_opts:
      type: none
      o: bind
      device: ${PATH_VM_WORDPRESS_NGINX}
secrets:
    db_name:
      file: ../secrets/db_name.txt
    db_user_name:
      file: ../secrets/db_user_name.txt
    db_user_password:
      file: ../secrets/db_user_password.txt
    db_root_password:
      file: ../secrets/db_root_password.txt
    db_hostname:
      file: ../secrets/db_hostname.txt
    wp_admin:
      file: ../secrets/wp_admin.txt
    wp_admin_password:
      file: ../secrets/wp_admin_password.txt
    wp_admin_email:
      file: ../secrets/wp_admin_email.txt
    wp_user_password:
      file: ../secrets/wp_user_password.txt
    wp_user_email:
      file: ../secrets/wp_user_email.txt
