version: '3.8'

networks:
  inception:
    driver: bridge

services:
  mariadb:
      container_name: ym_mariadb
      build:
        context: ./requirements/mariadb/
        dockerfile: Dockerfile
      image: mariadb
      restart: always
      networks:
        - inception
      volumes:
        - volume_mariadb:/var/lib/mysql
      ports:
        - "3306:3306"
      environment:
        MYSQL_DATABASE: ${NAME_DATABASE}
        MYSQL_USER: ${USER_NAME}
        MYSQL_PASSWORD: ${USER_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      secrets:
        - db_name
        - db_user_name
        - db_user_password
        - db_root_password



  wordpress:
      container_name: ym_wordpress
      build:
        context: ./requirements/wordpress
        dockerfile: Dockerfile
      image: wordpress
      restart: always
      volumes:
      - volume_wordpress_nginx:/var/www/html/wordpress
      networks:
        - inception
      expose:
        - "9000"
      depends_on:
      - mariadb
      environment:
        MYSQL_DATABASE : ${NAME_DATABASE}
        MYSQL_USER : ${USER_NAME}
        MYSQL_PASSWORD : ${USER_PASSWORD}
        LOCALHOST : ${DB_HOST}
        TITLE : ${TITLE}
        URL_WP : ${URL_WP}
        ADMIN_WP : ${ADMIN_WP}
        ADMIN_PASSWORD_WP : ${ADMIN_PASSWORD_WP}
        ADMIN_EMAIL_WP : ${ADMIN_EMAIL_WP}
        USER_WP : ${USER_WP}
        USER_PASSWORD_WP : ${USER_PASSWORD_WP}
        USER_EMAIL_WP : ${USER_EMAIL_WP}
        WP_REDIS_HOST: ${WP_REDIS_HOST}
        WP_REDIS_PORT : ${WP_REDIS_PORT}
      secrets:
        - db_name
        - db_user_name
        - db_user_password
        - db_hostname
        - wp_admin
        - wp_admin_password
        - wp_admin_email
        - wp_user_password
        - wp_user_email
        - wp_redis_host
        - wp_redis_port



  nginx:
        container_name: ym_nginx
        build:
          context: ./requirements/nginx
          dockerfile: Dockerfile
        image: nginx
        restart: always
        volumes:
        - volume_wordpress_nginx:/var/www/html/wordpress
        - volume_adminer:/var/www/html/adminer
        - volume_anon:/var/www/html/anon
        networks:
          - inception
        depends_on:
        - mariadb
        - wordpress
        ports:
        - "443:443"


  adminer:
        container_name: ym_adminer
        build:
          context: ./requirements/bonus/adminer
          dockerfile: Dockerfile
        image: adminer
        restart: always
        volumes:
          - volume_adminer:/var/www/html/adminer
        networks:
          - inception
        depends_on:
          - mariadb
          - wordpress
        expose:
          - "8081"



  anon:
        container_name: ym_anon
        build:
          context: ./requirements/bonus/site_statique
          dockerfile: Dockerfile
        image: anon
        restart: always
        volumes:
          - volume_anon:/var/www/html/anon
        networks:
          - inception
        depends_on:
          - nginx
        ports:
        - "3000:3000"

  cadvisor:
        container_name: ym_cadvisor
        build:
          context: ./requirements/bonus/cadvisor
          dockerfile: Dockerfile
        image: cadvisor
        restart: always
        ports:
          - "8080:8080"
        networks:
          - inception
        volumes:
        - /:/rootfs:ro
        - /var/run:/var/run:ro
        - /sys:/sys:ro
        - /var/lib/docker/:/var/lib/docker:ro




  redis:
        container_name: ym_redis
        build:
          context: ./requirements/bonus/redis
          dockerfile: Dockerfile
        image: redis
        restart: always
        volumes:
          - volume_wordpress_nginx:/var/www/html
        networks:
          - inception
        depends_on:
          - mariadb
          - wordpress
        ports:
          - '6379:6379'


  ftp-server:
      container_name: ym_ftp-server
      build:
        context: ./requirements/bonus/ftp-server
        dockerfile: Dockerfile
      image: ftp-server
      restart: always
      volumes:
        - "volume_wordpress_nginx:/var/www/html/ftp"
      ports:
        - "21:21"
        - "21100-21110:21100-21110"
      networks:
        - inception
      environment:
        FTP_USER: ${FTP_USER}
        FTP_PASSWORD: ${FTP_PASSWORD}
      secrets:
        - ftp_user
        - ftp_password


volumes:
  volume_mariadb:
    driver_opts:
      type: none
      o: bind
      device: ${PATH_VM_MARIADB}
  volume_wordpress_nginx:
    driver_opts:
      type: none
      o: bind
      device: ${PATH_VM_WORDPRESS_NGINX}
  volume_adminer:
    driver_opts:
      type: none
      o: bind
      device: ${PATH_VM_ADMINER}
  volume_anon:
    driver_opts:
      type: none
      o: bind
      device: ${PATH_VM_ANON}
secrets:
    db_name:
      file: ../secrets/db_name.txt
    db_user_name:
      file: ../secrets/db_user_name.txt
    db_user_password:
      file: ../secrets/db_user_password.txt
    db_root_password:
      file: ../secrets/db_root_password.txt
    db_hostname:
      file: ../secrets/db_hostname.txt
    wp_admin:
      file: ../secrets/wp_admin.txt
    wp_admin_password:
      file: ../secrets/wp_admin_password.txt
    wp_admin_email:
      file: ../secrets/wp_admin_email.txt
    wp_user_password:
      file: ../secrets/wp_user_password.txt
    wp_user_email:
      file: ../secrets/wp_user_email.txt
    wp_redis_host:
      file: ../secrets/wp_redis_host.txt
    wp_redis_port:
      file: ../secrets/wp_redis_port.txt
    ftp_user:
      file: ../secrets/ftp_user.txt
    ftp_password:
      file: ../secrets/ftp_password.txt

